[build]
  publish = ".next"
  command = "bash scripts/netlify-build.sh"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=optional"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Redirect rules for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  NODE_ENV = "production"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  NODE_ENV = "production"
